#if !canImport(ObjectiveC)
import XCTest

extension PlusOperatorTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PlusOperatorTests = [
        ("testAddToArrayValue", testAddToArrayValue),
        ("testAddToBoolValue", testAddToBoolValue),
        ("testAddToDoubleValue", testAddToDoubleValue),
        ("testAddToInfinityValue", testAddToInfinityValue),
        ("testAddToIntegerValue", testAddToIntegerValue),
        ("testAddToMapValue", testAddToMapValue),
        ("testAddToNaNValue", testAddToNaNValue),
        ("testAddToNullValue", testAddToNullValue),
        ("testAddToStringValue", testAddToStringValue),
    ]
}

extension SanitizerTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SanitizerTests = [
        ("testCleanHtml", testCleanHtml),
        ("testTagWhitelisting", testTagWhitelisting),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(PlusOperatorTests.__allTests__PlusOperatorTests),
        testCase(SanitizerTests.__allTests__SanitizerTests),
    ]
}
#endif
