#if !canImport(ObjectiveC)
import XCTest

extension TimesOperatorTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TimesOperatorTests = [
        ("testMultiplyWithArrayValue", testMultiplyWithArrayValue),
        ("testMultiplyWithBoolValue", testMultiplyWithBoolValue),
        ("testMultiplyWithDoubleValue", testMultiplyWithDoubleValue),
        ("testMultiplyWithInfinityValue", testMultiplyWithInfinityValue),
        ("testMultiplyWithIntegerValue", testMultiplyWithIntegerValue),
        ("testMultiplyWithMapValue", testMultiplyWithMapValue),
        ("testMultiplyWithNaNValue", testMultiplyWithNaNValue),
        ("testMultiplyWithNullValue", testMultiplyWithNullValue),
        ("testMultiplyWithStringValue", testMultiplyWithStringValue),
    ]
}

extension MinusOperatorTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MinusOperatorTests = [
        ("testSubstractFromArrayValue", testSubstractFromArrayValue),
        ("testSubstractFromBoolValue", testSubstractFromBoolValue),
        ("testSubstractFromDoubleValue", testSubstractFromDoubleValue),
        ("testSubstractFromInfinityValue", testSubstractFromInfinityValue),
        ("testSubstractFromIntegerValue", testSubstractFromIntegerValue),
        ("testSubstractFromMapValue", testSubstractFromMapValue),
        ("testSubstractFromNaNValue", testSubstractFromNaNValue),
        ("testSubstractFromNullValue", testSubstractFromNullValue),
        ("testSubstractFromStringValue", testSubstractFromStringValue),
    ]
}

extension PlusOperatorTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PlusOperatorTests = [
        ("testAddToArrayValue", testAddToArrayValue),
        ("testAddToBoolValue", testAddToBoolValue),
        ("testAddToDoubleValue", testAddToDoubleValue),
        ("testAddToInfinityValue", testAddToInfinityValue),
        ("testAddToIntegerValue", testAddToIntegerValue),
        ("testAddToMapValue", testAddToMapValue),
        ("testAddToNaNValue", testAddToNaNValue),
        ("testAddToNullValue", testAddToNullValue),
        ("testAddToStringValue", testAddToStringValue),
    ]
}

extension SanitizerTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SanitizerTests = [
        ("testCleanHtml", testCleanHtml),
        ("testTagWhitelisting", testTagWhitelisting),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(TimesOperatorTests.__allTests__TimesOperatorTests),
        testCase(MinusOperatorTests.__allTests__MinusOperatorTests),
        testCase(PlusOperatorTests.__allTests__PlusOperatorTests),
        testCase(SanitizerTests.__allTests__SanitizerTests),
    ]
}
#endif
